services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./varnish:/etc/varnish
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./php
    volumes:
      - ./php:/var/www/html
      - ./php-fpm:/etc/php/8.1/fpm
    environment:
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LANGUAGE=${LANGUAGE}
      - CURRENCY=${CURRENCY}
      - TIMEZONE=${TIMEZONE}
      - SEARCH_ENGINE=${SEARCH_ENGINE}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - USE_REWRITES=${USE_REWRITES}
      - BACKEND_FRONTNAME=${BACKEND_FRONTNAME}
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      LOG_BIN_TRUST_FUNCTION_CREATORS: '1'
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
